name: build-steps
description: 'steps to build R3BRoot and ucesb'


inputs:
  build-needed:
    description: 'build process is needed'
    required: false
    default: 'true'

runs:
  using: composite
  steps:
    - if: ${{ matrix.url }}
      name: add other repos
      run: |
        cd $GITHUB_WORKSPACE
        for url in ${{ matrix.url }};
        do
          git clone -b dev ${url}
        done
      shell: bash

    - name: cmake config ${{ matrix.repos }}
      run: |
        git config --global --add safe.directory $GITHUB_WORKSPACE
        git submodule update --init --recursive
        git clone https://github.com/R3BRootGroup/macros.git
        echo ""
        echo "path environment variable: $PATH\n"
        echo ""
        cmake --preset ${{ matrix.preset }} . -C "$GITHUB_WORKSPACE/cmake/CI_CD/configure_options.cmake"
      shell: bash

    - name: build ${{ matrix.repos }}
      if: inputs.build-needed == 'true'
      run: |
        cmake --build ./build -- -j ${NUM_THREADS}
      shell: bash
